locale = "uk"
label = "Українська"
displayName = "Українська"
weight = 19
title = "Hyper Bridge"

[params]
  displayName = "Українська"
  isoCode = "uk"
  dateFormat = "2 January 2006"
  logo = "img/logo.svg"
  description = "Hyper Bridge unlocks the native visual notification system of HyperOS, allowing third-party apps to utilize the HyperIsland."
  copyright = "© 2026 D4vidDf. All rights reserved."

[params.author]
  name = "Hyper Bridge"
  image = "img/logo.svg"
  headline = "Expand your Super Island"
  bio = "Hyper Bridge unlocks the native visual notification system of HyperOS, allowing third-party apps to utilize the HyperIsland."
  links = [
    { github = "https://github.com/D4vidDf/HyperBridge" },
    { globe = "https://crowdin.com/project/hyperbridge" }
  ]
