[[main]]
  name = "Docs"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "Changelog"
  pageRef = "changelog"
  weight = 20

[[main]]
  url = "https://play.google.com/store/apps/details?id=com.d4viddf.hyperbridge"
  weight = 25
  pre = "google-play"
  title = "Google Play"

[[main]]
  url = "https://github.com/D4vidDf/HyperBridge"
  weight = 30
  pre = "github"
  title = "GitHub"
