colorScheme = "hyperbridge"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
logo = "img/logo.svg"

[header]
  layout = "floating"
  logo = "img/logo.svg"
  showTitle = true
  mobileMenuStyle = "dropdown"

[homepage]
  layout = "landing"
  showRecent = false
  cardView = true

[docs]
  versionBadge = "v0.6.0 (dev)"
  versionBadgeTextSize = "16px"

[article]
  showDate = true
  showAuthor = false
  showReadingTime = true
  showTableOfContents = true
  showBreadcrumbs = true

[list]
  showBreadcrumbs = true
  showTableOfContents = true
  cardView = true

[footer]
  showCopyright = true
  showTheme = false
